
# Subject
sid: 676
conv_ids: np.arange(1, 79)
elecs: np.arange(1, 126)
sig_elec_file_comp: 'sig-elecs/20230723-tfs-sig-file/tfs-sig-file-glove-676-comp.csv'
sig_elec_file_prod: 'sig-elecs/20230723-tfs-sig-file/tfs-sig-file-glove-676-prod.csv'